### ISSUE TITLE
ErrorException Undefined offset: 1

### ISSUE THREAD

**Issue by Bitsnoxx** [TechnicPack/TechnicSolder#219]
Hey! I have an error, which I haven`t managed to figured out :c

On login I get this: 
```
exception 'ErrorException' with message 'Undefined offset: 1' in /home/bitsnoxx/public_html/Soldier/app/libraries/UpdateUtils.php:124
Stack trace:
#0 /home/bitsnoxx/public_html/Soldier/app/libraries/UpdateUtils.php(124): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/home/bitsnoxx/...', 124, Array)
#1 /home/bitsnoxx/public_html/Soldier/app/libraries/UpdateUtils.php(81): UpdateUtils::getLocalChangeLog()
#2 /home/bitsnoxx/public_html/Soldier/app/controllers/DashboardController.php(16): UpdateUtils::getChangeLog()
#3 [internal function]: DashboardController->getIndex()
#4 /home/bitsnoxx/public_html/Soldier/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#5 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(5834): Illuminate\Routing\Controller->callAction('getIndex', Array)
#6 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(5822): Illuminate\Routing\ControllerDispatcher->call(Object(DashboardController), Object(Illuminate\Routing\Route), 'getIndex')
#7 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(5027): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'DashboardContro...', 'getIndex')
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(5385): call_user_func_array(Object(Closure), Array)
#10 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(5052): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#12 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#15 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /home/bitsnoxx/public_html/Soldier/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 /home/bitsnoxx/public_html/Soldier/public/index.php(49): Illuminate\Foundation\Application->run()
#20 {main}
```

Thanks!

**Comment by fcpwiz** [comment]
Are you installing Solder from scratch, or updating?

**Comment by Bitsnoxx** [comment]
From scratch

**Comment by fcpwiz** [comment]
I literally had the same error 3 hours ago, but I can't remember what I did to fix it.

**Comment by fcpwiz** [comment]
Do you have all of these installed?

PHP
PHP MCrypt
PHP Curl
PHP GD
MySQL
Composer
FileInfo
Mbstring

**Comment by Bitsnoxx** [comment]
PHP, MCrypt,Curl,GD,FileInfo,MBString = Yes
Composer = Yes


PHP Version 5.4.35

**Comment by GenPage** [comment]
From your solder root folder please run.

`git describe --abbrev=0 --tags`

`git log --pretty=format:%H~%h~%ar~%s v0.7.0.6..v0.7.0.7`

**Comment by Bitsnoxx** [comment]
I did`nt clone the repo, sorry! I did run composer to install the files from composer.json though

**Comment by GenPage** [comment]
you need to clone the repo

**Comment by Bitsnoxx** [comment]
Okay, thanks!
