### ISSUE TITLE
Mods can't be downloaded

### ISSUE THREAD

**Issue by DurtyFree** [TechnicPack/TechnicSolder#285]
Heya,
I just reinstalled my TechnicSolder installation by using the actual Guide.

I added many mods with a couple of versions, about ~70 Mods are now in my mod library. I also added an old modpack of mine (Which I years ago maintained with TechnicSolder), everything seemed to be fine. 
Until I tried to download / install the modpack via the launcher.
It gives me the following error:
"Error downloading a file for the following pack: Industrial Lemon Reloaded
 
Invalid URL:

Please consult the modpack author."

The TechnicPack log gives me this error:
```
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] net.technicpack.rest.RestfulAPIException: Error accessing URL [http://solder.minecraft.at/public/api/modpack/]
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:108)
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] 	at net.technicpack.launchercore.modpacks.PackLoadJob$6.run(PackLoadJob.java:195)
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] 	at java.lang.Thread.run(Unknown Source)
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] Caused by: java.io.FileNotFoundException: http://solder.minecraft.at/api/modpack
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:88)
[B#256] 2015/01/28 19:36:47 [SCHWERWIEGEND] 	... 7 more
[B#256] 2015/01/28 19:36:47 [INFORMATION] Starting download of http://cdn.technicpack.net/platform2/pack-icons/576270.png?1422391888, with 3 tries remaining
[B#256] 2015/01/28 19:36:47 [INFORMATION] Starting download of http://cdn.technicpack.net/platform2/pack-icons/576270.png?1422391888, with 3 tries remaining
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] net.technicpack.rest.RestfulAPIException: Error accessing URL [http://solder.minecraft.at/public/api/modpack/]
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:108)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.launchercore.modpacks.PackLoadJob$6.run(PackLoadJob.java:195)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at java.lang.Thread.run(Unknown Source)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] Caused by: java.io.FileNotFoundException: http://solder.minecraft.at/api/modpack
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:88)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	... 7 more
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] net.technicpack.rest.RestfulAPIException: Error accessing URL [http://solder.minecraft.at/public/api/modpack/]
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:108)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.launchercore.modpacks.PackLoadJob$6.run(PackLoadJob.java:195)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at java.lang.Thread.run(Unknown Source)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] Caused by: java.io.FileNotFoundException: http://solder.minecraft.at/api/modpack
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:88)
[B#256] 2015/01/28 19:36:48 [SCHWERWIEGEND] 	... 7 more
```

So I checked my solder configuration, and the mod paths are correct. I can even download the mods via the mod url which is shown in the versions tab (in the web interface)
So I tried to get on http://solder.minecraft.at/public/api/modpack to see what happens, and it gave me back the correct string.

Then I checked why it tells me the wrong url in the FileNotFoundException, and after a couple of hours I found the bug.
Its a strange behaviour, for some reason http://solder.minecraft.at/public/api/modpack leads to the correct file but http://solder.minecraft.at/public/api/modpack/ (with a trailing slash) doesnt. It redirects the url back to the whole url but without the "public" in it.

Thats kinda weird and I already tried to fix this but I guess its an internal bug or something.

And I am not able to set the public folder to the base directory of the website. Because its administrated over iMSCP which only allows me to upload things into a htdocs folder.

Hope somebody is able to help me.

**Comment by TheGeekdu74** [comment]
Why you put /api/ to download a mod ??? /api/ is for link the solder.

**Comment by sct** [comment]
This is a bug with your setup. Both should work with the default .htaccess if you are using apache. If you are using nginx you need to have a better rewrite (I believe it should force remove the trailing slash). Try the following: https://gist.github.com/sct/26e29186ab4736b5f3c3
