### ISSUE TITLE
error: Internal Server Error when adding mod version

### ISSUE THREAD

**Issue by Sodierlow** [TechnicPack/TechnicSolder#335]
Hello,
i got this error whent trying to add mod version
>[2015-03-06 05:21:31] production.ERROR: exception 'ErrorException' with message 'file_exists(): open_basedir restriction in effect. File(/var/www/vhost/nticom.ovh/solder/public/mods/buildcraft/buildcraft-v3.4.3.zip) is not within the allowed path(s): (/var/www/vhosts/nticom.ovh/:/tmp/)' in /var/www/vhosts/nticom.ovh/solder/app/controllers/ModController.php:243
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'file_exists(): ...', '/var/www/vhosts...', 243, Array)
#1 /var/www/vhosts/nticom.ovh/solder/app/controllers/ModController.php(243): file_exists('/var/www/vhost/...')
#2 /var/www/vhosts/nticom.ovh/solder/app/controllers/ModController.php(191): ModController->mod_md5(Object(Mod), 'v3.4.3')
#3 [internal function]: ModController->anyAddVersion()
#4 /var/www/vhosts/nticom.ovh/solder/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#5 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(5843): Illuminate\Routing\Controller->callAction('anyAddVersion', Array)
#6 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(5831): Illuminate\Routing\ControllerDispatcher->call(Object(ModController), Object(Illuminate\Routing\Route), 'anyAddVersion')
#7 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(5036): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ModController', 'anyAddVersion')
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(5394): call_user_func_array(Object(Closure), Array)
#10 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(5061): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(5049): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#12 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(7821): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(8428): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(8375): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(11038): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/vhosts/nticom.ovh/solder/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 /var/www/vhosts/nticom.ovh/solder/public/index.php(49): Illuminate\Foundation\Application->run()
#20 {main} [] []

any idea??

**Comment by Sodierlow** [comment]
ok Solved
for help look this if you use plesk
> http://forum.sp.parallels.com/threads/php-open_basedir-restriction-adding-paths-not-working.290011/
