### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by Thakao** [TechnicPack/TechnicSolder#628]
Installed Solder on an Debian-87-jessie-64 with a LAMP stack, but I've got some issues with downloading the mods. 

When I'm in ```mydomain.me/index.php/```mod/list and try to download a mod an error occurs "Mod not found" 

Also when I'm downloading the pack via the launcher the same issue ```Invalid URL:/mod/jadjadjad-v1.zip``` occurs. 

I haven't changed any of the configs, so the patch to my mods is  ```/var/www/TechnicSolder/public/mods```.
Solder recognizes the mod when adding them to the mod-list.

**Comment by spannerman79** [comment]
In solder you can actually check to see if you can download the mod yourself in the mod library under Download URL. 

Secondly turn on debugging http://docs.solder.io/docs/faq-frequently-asked-questions
Basically RTFM

**Comment by Thakao** [comment]
Have tried to download the mod via Download URL : 
> Mod not found 
also in debug mode no error output

**Comment by Thakao** [comment]
the log file shows this
```[2017-02-22 07:41:26] production.INFO: Fable of Glory: Attempting to add modpack perm to user - admin - Modpack perm empty [] []
[2017-02-22 07:42:15] production.ERROR: exception 'ErrorException' with message 'Undefined index: mods' in /var/www/TechnicSolder/app/controllers/ApiController.php:105
Stack trace:
#0 /var/www/TechnicSolder/app/controllers/ApiController.php(105): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/Techni...', 105, Array)
#1 [internal function]: APIController->getMod()
#2 /var/www/TechnicSolder/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/TechnicSolder/bootstrap/compiled.php(3819): Illuminate\Routing\Controller->callAction('getMod', Array)
#4 /var/www/TechnicSolder/bootstrap/compiled.php(3807): Illuminate\Routing\ControllerDispatcher->call(Object(APIController), Object(Illuminate\Routing\Route), 'getMod')
#5 /var/www/TechnicSolder/bootstrap/compiled.php(3012): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ApiController', 'getMod')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/TechnicSolder/bootstrap/compiled.php(3370): call_user_func_array(Object(Closure), Array)
#8 /var/www/TechnicSolder/bootstrap/compiled.php(3037): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/TechnicSolder/bootstrap/compiled.php(3025): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/TechnicSolder/bootstrap/compiled.php(702): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/TechnicSolder/bootstrap/compiled.php(678): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/TechnicSolder/bootstrap/compiled.php(5797): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/TechnicSolder/bootstrap/compiled.php(6404): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/TechnicSolder/bootstrap/compiled.php(6351): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/TechnicSolder/bootstrap/compiled.php(8367): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/TechnicSolder/bootstrap/compiled.php(639): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /var/www/TechnicSolder/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2017-02-22 07:42:29] production.ERROR: exception 'ErrorException' with message 'Undefined index: mods' in /var/www/TechnicSolder/app/controllers/ApiController.php:105
Stack trace:
#0 /var/www/TechnicSolder/app/controllers/ApiController.php(105): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/Techni...', 105, Array)
#1 [internal function]: APIController->getMod()
#2 /var/www/TechnicSolder/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/TechnicSolder/bootstrap/compiled.php(3819): Illuminate\Routing\Controller->callAction('getMod', Array)
#4 /var/www/TechnicSolder/bootstrap/compiled.php(3807): Illuminate\Routing\ControllerDispatcher->call(Object(APIController), Object(Illuminate\Routing\Route), 'getMod')
#5 /var/www/TechnicSolder/bootstrap/compiled.php(3012): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ApiController', 'getMod')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/TechnicSolder/bootstrap/compiled.php(3370): call_user_func_array(Object(Closure), Array)
#8 /var/www/TechnicSolder/bootstrap/compiled.php(3037): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/TechnicSolder/bootstrap/compiled.php(3025): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/TechnicSolder/bootstrap/compiled.php(702): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/TechnicSolder/bootstrap/compiled.php(678): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/TechnicSolder/bootstrap/compiled.php(5797): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/TechnicSolder/bootstrap/compiled.php(6404): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/TechnicSolder/bootstrap/compiled.php(6351): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/TechnicSolder/bootstrap/compiled.php(8367): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/TechnicSolder/bootstrap/compiled.php(639): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /var/www/TechnicSolder/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2017-02-22 07:42:37] production.ERROR: exception 'ErrorException' with message 'Undefined index: mods' in /var/www/TechnicSolder/app/controllers/ApiController.php:105
Stack trace:
#0 /var/www/TechnicSolder/app/controllers/ApiController.php(105): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/Techni...', 105, Array)
#1 [internal function]: APIController->getMod()
#2 /var/www/TechnicSolder/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/TechnicSolder/bootstrap/compiled.php(3819): Illuminate\Routing\Controller->callAction('getMod', Array)
#4 /var/www/TechnicSolder/bootstrap/compiled.php(3807): Illuminate\Routing\ControllerDispatcher->call(Object(APIController), Object(Illuminate\Routing\Route), 'getMod')
#5 /var/www/TechnicSolder/bootstrap/compiled.php(3012): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ApiController', 'getMod')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/TechnicSolder/bootstrap/compiled.php(3370): call_user_func_array(Object(Closure), Array)
#8 /var/www/TechnicSolder/bootstrap/compiled.php(3037): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/TechnicSolder/bootstrap/compiled.php(3025): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/TechnicSolder/bootstrap/compiled.php(702): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/TechnicSolder/bootstrap/compiled.php(678): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/TechnicSolder/bootstrap/compiled.php(5797): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/TechnicSolder/bootstrap/compiled.php(6404): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/TechnicSolder/bootstrap/compiled.php(6351): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/TechnicSolder/bootstrap/compiled.php(8367): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/TechnicSolder/bootstrap/compiled.php(639): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /var/www/TechnicSolder/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2017-02-22 07:51:51] production.INFO: Found 'mods/damage-indicators/damage-indicators-v6.3.1MC1.7.10.zip' [] []
[2017-02-22 11:33:39] production.INFO: Found 'mods/damage-indicators/damage-indicators-v6.3.1MC1.7.10.zip' [] []```

**Comment by skwerlman** [comment]
what are the values of `repo_location` and `mirror_url` in `app/config/solder.php`?

**Comment by Thakao** [comment]
Haven't changed anything.
`'repo_location' => '',`
`'mirror_url' => '',`

**Comment by skwerlman** [comment]
You need to fill those out. Please read the installation instructions carefully before creating issues here.

**Comment by Thakao** [comment]
my fault skipped the configuration
