### ISSUE TITLE
Solder API-Endpoint refers to a wrong URL

### ISSUE THREAD

**Issue by Sendarox** [TechnicPack/TechnicSolder#650]
Hello,
today I set up the TechnicSolder and linked it with TechnicPack.net. But the TechnicLauncher can't access to the Solder-API.

> [B#353] net.technicpack.rest.RestfulAPIException: Error accessing URL [https://mirror.edgelessgaming.com/public/api/modpack/]
[B#353] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:157)
[B#353] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#353] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#353] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#353] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#353] 	at net.technicpack.platform.PlatformPackInfoRepository.getCompletePackInfo(PlatformPackInfoRepository.java:51)
[B#353] 	at net.technicpack.launchercore.modpacks.PackLoadJob$6.run(PackLoadJob.java:190)
[B#353] 	at java.lang.Thread.run(Thread.java:745)

If I load the API-page in my brower, it refers to another URL ("mirror.edgelessgaming.com/api/modpack/" instead of "mirror.edgelessgaming.com/**public**/api/modpack/"). If I remove the last slash in the URL (mirror.edgelessgaming.com/public/api/modpack) it works fine.

Is this problem known and how to fix it?

**Comment by Sendarox** [comment]
My fault. Solder was not installed in the root directory of the Apache-Web-Server.
